services:
  - type: web
    name: foodster-backend
    env: node
    rootDir: foodster-backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
